// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8_NR5Mz3VfEVwwwKonFDcyp7tsJqQrRk',
    appId: '1:402762767084:web:fcfd4d38caba695ade23c9',
    messagingSenderId: '402762767084',
    projectId: 'bookverse-c4033',
    authDomain: 'bookverse-c4033.firebaseapp.com',
    storageBucket: 'bookverse-c4033.appspot.com',
    measurementId: 'G-M1XF4P7PXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqfQkFX0yEXsAzj7wKFGJ6qpt4dIys3MI',
    appId: '1:402762767084:android:ed8b59f8cf87e704de23c9',
    messagingSenderId: '402762767084',
    projectId: 'bookverse-c4033',
    storageBucket: 'bookverse-c4033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPeXSLvesGK8wllBqkZpZ2_rT0MOL0YDA',
    appId: '1:402762767084:ios:c9dc113a23dda17ade23c9',
    messagingSenderId: '402762767084',
    projectId: 'bookverse-c4033',
    storageBucket: 'bookverse-c4033.appspot.com',
    iosBundleId: 'com.example.bookVerse',
  );
}
